 language: node_js
 node_js: 
  - "8"
 services:
    - mongodb
 cache:
   directories:
     - node_modules
 script:
   - npm run build
   - npm test

 deploy:
   provider: script
   skip_cleanup: true
   on:
     branch: master
  
  install:
    - npm ci
