 language: node_js
 node_js: 
  - "9"
 services:
    - mongodb
 cache:
   directories:
     - node_modules
 script:
   - npm run build
   - npm test
 env:
   - CI=true

 deploy:
   provider: script
   skip_cleanup: true
   on:
     branch: master

