 language: node_js
 node_js: 
  - node
 services:
    - mongodb
 cache:
   directories:
     - node_modules
 script:
   - npm run build
   - npm test

 deploy:
   provider: script
   skip_cleanup: true
   on:
     branch: master
  
  install:
    - npm ci

  before-install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest